set $terminal ghostty
set $launcher "rofi -show drun"
set $control_center "qs -c noctalia-shell ipc call controlCenter toggle"
set $settings "qs -c noctalia-shell ipc call settings toggle"
set $locker "hyprlock"

bindsym $mod+Return exec $terminal
bindsym $mod+d exec $launcher
bindsym $mod+c exec $control_center
bindsym $mod+s exec $settings
bindsym $mod+Delete exec $locker

bindsym Print exec ~/.config/sway/scripts/screenshot.fish
bindsym $mod+Print exec ~/.config/sway/scripts/screenshot.fish full
