set $terminal ghostty
set $launcher rofi -show drun
set $locker swaylock

bindsym $mod+Return exec $terminal
bindsym $mod+d      exec $launcher
bindsym $mod+Delete exec $locker

bindsym Print      exec ~/.config/sway/scripts/screenshot.fish
bindsym $mod+Print exec ~/.config/sway/scripts/screenshot.fish full
