floating_modifier $mod

output eDP-1 bg ~/Pictures/1.jpg fit

input "type:touchpad" {
    dwt enabled
    tap enabled
    middle_emulation enabled
    natural_scroll enabled
}

input "type:keyboard" {
    xkb_layout us,ara
    xkb_options ctrl:swapcaps,grp:alt_shift_toggle
    repeat_rate 125
    repeat_delay 250
}
