assign [app_id=discord] workspace number 10

for_window [app_id="com.gabm.satty"] {
	floating enable
	resize set width 1632 px height 918 px
	move position center
	border 10
}

for_window [workspace=1 tiling app_id="^$" title="^$"] {
    floating enable
    move position cetner
    move up 80
} 

for_window [app_id="^hyprland-share-picker$"] {
    floating enable
}

for_window [app_id="^org.pulseaudio.pavucontrol$"] {
	floating enable
	resize set width 900 px height 900 px
}
