general {
    hide_cursor = true
    ignore_empty_input = true
	text_trim = true
	immediate_render = true
	fail_timeout = 500
}

auth {
	fingerprint {
		enabled = true
		present_message = Nice Finger :)
	}
}

animations {
	enabled = false
}

background {
    monitor =
    path = ~/Pictures/1.jpg
    blur_passes = 3
    blur_size = 3
}

input-field {
    monitor =
    size = 30%, 7%
    position = 0, -120
	hide_input = true
    fade_on_empty = false
    rounding = 12
    outline_thickness = 2
    shadow_passes = 2
    shadow_size = 6

    outer_color = rgba(255, 255, 255, 0.08)
    inner_color = rgba(0, 0, 0, 0.35)
    font_color = rgba(255, 255, 255, 0.9)

    placeholder_text = Hello There
    placeholder_color = rgba(255, 255, 255, 0.4)

    check_text = One Minute...
    check_color = rgba(120, 200, 255, 1.0)

    fail_text = Nice Try :)
    fail_color = rgba(255, 80, 80, 1.0)
}

shape {
	monitor = 
	size = 350, 100
	rounding = 12
	border_size = 2
	position = 0, 120
    border_color = rgba(255, 255, 255, 0.08)
    color = rgba(0, 0, 0, 0.35)
    shadow_passes = 3
    shadow_size = 20
}

label {
    monitor =
    position = 0, 120
    text = $TIME12
    font_size = 48
    color = rgba(255, 255, 255, 0.95)
    shadow_passes = 2
    shadow_size = 8
}
