enable_esc_key = true
position       = "Bottom"
layer          = "Top"



[osd]
enabled                    = true
timeout                    = 1500
show_volume_percentage     = true
show_brightness_percentage = true



[modules]
left   = [ "Workspaces" ]
center = [ "Tempo" ]
right  = [ [ "Privacy", "Settings", "Notifications" ] ]



[appearance]
font_name = "Liberation Mono Nerd Font"
scale_factor = 1.25
style = "Solid"

opacity = 0.0
menu.opacity = 1.0

success_color = "#a6e3a1"
warning_color = "#f9e2af"
danger_color = "#f38ba8"
text_color = "#cdd6f4"

workspace_colors = [ "#fab387", "#b4befe", "#cba6f7" ]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"
