assign [app_id=discord]		 workspace number 10
assign [app_id=brave-origin] workspace number 1

for_window [app_id="com.gabm.satty"] {
	floating enable
	resize set width 1632 px height 918 px
	move position center
	border 10
}

for_window [app_id="^brave-origin$" title="^Sign in - Google Accounts - Brave Origin$"] {
    floating enable
} 

for_window [app_id="^hyprland-share-picker$"] {
    floating enable
}

for_window [app_id="^org.pulseaudio.pavucontrol$"] {
	floating enable
	resize set width 900 px height 900 px
}
